camel.main.name=saludvital-integration
camel.main.duration-max-seconds=-1

saludvital.input.dir=data/input
saludvital.output.dir=data/output
saludvital.archive.dir=data/archive
saludvital.error.dir=data/error
